#######################
### PATH MANAGEMENT ###
#######################

ANNOTATION_PATH: "/home/taheera.ahmed/data/reindeerdrone/result.json"
IMAGES_FOLDER_PATH: "/home/taheera.ahmed/data/reindeerdrone/"

TILE_ANNOTATION_PATH: "/home/taheera.ahmed/data/reindeerdrone/tiles/new_annotations.json"
TILE_FOLDER_PATH: "/home/taheera.ahmed/data/reindeerdrone/tiles"

###################
# DATA PROCESSING #
###################

TILE_SIZE: 1024
OVERLAP: 100
PLOT_ANNOTATION: False

###############
# PREDICTIONS #
###############

CONFIG_FILE: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
MODEL_WEIGHTS: "../../output/model_final.pth"  # Path to the trained model weights
OUTPUT_FOLDER: "../../predict/"
PLOT_PREDICTION: True
